name: Check Version
description: Make sure the version number of the Take Counter components match
inputs:
  packages:
    description: Paths to package.json files
    required: true
runs:
  using: node20
  main: 'dist/index.js'
