name: Build and Deploy Electron App

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: deployment environment
        required: true
    secrets:
      S3_ID:
        required: true
      S3_SECRET:
        required: true
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: deployment environment
        required: true
    secrets:
      S3_ID:
        required: true
      S3_SECRET:
        required: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: universal
            target: darwin

    runs-on: ${{ matrix.os }}

    env:
      electron-directory: ./electron
      web-directory: ./web
      distributable-path: "electron/out/make/zip/${{ matrix.target }}/${{ matrix.arch }}/*.zip"
      artifact-name: "${{ matrix.target }}-${{ matrix.arch }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build Electron App
        run: npm run make -- --arch ${{ matrix.arch }} --platform ${{ matrix.target }}
        working-directory: ${{ env.electron-directory }}
      - name: Upload App to Workflow Run
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact-name }}
          path: ${{ env.distributable-path }}
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Retrieve build
        uses: actions/download-artifact@v4
      - run: mkdir artifacts
      - run: mv ./**/*.zip artifacts
      - name: Upload App to S3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ./artifacts/
          destination: s3://${{ vars.S3_BUCKET }}/
          aws_access_key_id: ${{ secrets.S3_ID }}
          aws_secret_access_key: ${{ secrets.S3_SECRET }}
          aws_region: ${{ vars.S3_REGION }}
          flags: --recursive --include "*.zip"
