name: Test Common Libraries

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install commons
        uses: ./.github/actions/install-common
      - name: Lint
        run: npm run lint
        working-directory: ./common
      - name: Test
        run: npm test
        working-directory: ./common
